version: '2.1'

services:
  vpn:
    image: harveyphoenix/docker-ipsec-vpn-server
    networks:
      - ipsecnet
    restart: always
    env_file:
      - ./vpn.env
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
    privileged: true
    hostname: ipsec-vpn-server
    container_name: ipsec-vpn-server
    volumes:
      - /lib/modules:/lib/modules:ro
networks:
    ipsecnet:
      name: ipsecvpn
      driver: bridge
      enable_ipv6: false
      ipam:
        driver: default
        # config:
        #   - subnet: 172.15.234.0/24
